apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-fetcher
  namespace: default
  labels:
    app.kubernetes.io/name: link-fetcher
    app.kubernetes.io/instance: link-fetcher
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/component: cli
    app.kubernetes.io/part-of: link-fetcher
    app.kubernetes.io/managed-by: kubectl
spec:
  replicas: 1
  revisionHistoryLimit: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: link-fetcher
      app.kubernetes.io/instance: link-fetcher
  template:
    metadata:
      labels:
        app.kubernetes.io/name: link-fetcher
        app.kubernetes.io/instance: link-fetcher
        app.kubernetes.io/version: "0.0.1"
        app.kubernetes.io/component: cli
        app.kubernetes.io/part-of: link-fetcher
        app.kubernetes.io/managed-by: kubectl
    spec:
      automountServiceAccountToken: false

      securityContext:
        runAsNonRoot: true
        runAsGroup: 1000
        runAsUser: 1000
        fsGroup: 1000

      containers:
      - name: link-fetcher
        image: ttl.sh/link-fetcher:latest
        imagePullPolicy: IfNotPresent

        args:
        - https://news.ycombinator.com/

        env:
        - name: OUTPUT
          value: "json"
        - name: SLEEP
          value: "true"

        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 50m
            memory: 64Mi

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          privileged: false
          capabilities:
            drop:
            - ALL
