name: Build
on:
  workflow_dispatch:
  push:
    branches: [ "*" ]
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      SHUTUP: 1
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: build
      uses: dagger/dagger-for-github@v6
      with:
        version: "0.14.0"
        call: build
