name: Build
on:
  workflow_dispatch:
  push:
    branches: [ "*" ]
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      SHUTUP: 1
    steps:
    - id: checkout
      name: Checkout
      uses: actions/checkout@v4

    - id: build
      name: Build & Push
      uses: dagger/dagger-for-github@v7
      with:
        engine-stop: "false"
        version: "latest"
        call: build

    - id: scan
      name: Scan the image for security vulnerability
      uses: dagger/dagger-for-github@v7
      with:
        version: "latest"
        call: scan
