name: Deploy
on:
  # workflow_run:
  #   workflows: [ "Build" ]
  #   types: [ "completed" ]
  workflow_dispatch:
  push:
    branches: [ "*" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      SHUTUP: 1
    steps:
    - id: checkout
      name: checkout
      uses: actions/checkout@v4

    - id: minikube
      name: Start Minikube
      uses: medyagh/setup-minikube@v0.0.18
      with:
        kubernetes-version: "1.31.0"
        minikube-version: "1.34.0"

    - id: get-ip
      run: echo "MINIKUBE_IP=$(minikube ip)" >> $GITHUB_ENV

    - name: deploy
      uses: dagger/dagger-for-github@v7
      with:
        version: "latest"
        call: deploy --kubeconfig="$HOME/.kube/config" --kube="tcp://$MINIKUBE_IP:8443" --kube-port=8443 --certs="$HOME/.minikube" --certs-path="$HOME/.minikube" --insecure

    - name: status
      uses: dagger/dagger-for-github@v7
      with:
        version: "latest"
        call: status --kubeconfig="$HOME/.kube/config" --kube="tcp://$MINIKUBE_IP:8443" --kube-port=8443 --certs="$HOME/.minikube" --certs-path="$HOME/.minikube" --insecure

    - name: validate
      uses: dagger/dagger-for-github@v7
      with:
        version: "latest"
        call: validate --kubeconfig="$HOME/.kube/config" --kube="tcp://$MINIKUBE_IP:8443" --kube-port=8443 --certs="$HOME/.minikube" --certs-path="$HOME/.minikube" --insecure
