name: Deploy
on:
  workflow_dispatch:
  workflow_run:
    workflows: [ Build ]
    types: [ completed ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      SHUTUP: 1
    steps:
    - id: checkout
      name: Checkout
      uses: actions/checkout@v4

    - id: minikube
      name: Start Minikube
      uses: medyagh/setup-minikube@v0.0.18
      with:
        kubernetes-version: "1.31.0"
        minikube-version: "1.34.0"

    - id: get-ip
      name: Get Minikube IP
      run: echo "MINIKUBE_IP=$(minikube ip)" >> $GITHUB_ENV

    - id: deploy
      name: Deploy Link Fetcher
      uses: dagger/dagger-for-github@v7
      with:
        engine-stop: "false"
        version: "latest"
        call: deploy --kubeconfig="$HOME/.kube/config" --kube="tcp://$MINIKUBE_IP:8443" --kube-port=8443 --certs="$HOME/.minikube" --certs-path="$HOME/.minikube" --insecure

    - id: status
      name: Wait for Link Fetcher rollout to complete
      uses: dagger/dagger-for-github@v7
      with:
        engine-stop: "false"
        version: "latest"
        call: status --kubeconfig="$HOME/.kube/config" --kube="tcp://$MINIKUBE_IP:8443" --kube-port=8443 --certs="$HOME/.minikube" --certs-path="$HOME/.minikube" --insecure

    - id: validate
      name: Validate Link Fetcher is working
      uses: dagger/dagger-for-github@v7
      with:
        version: "latest"
        call: validate --kubeconfig="$HOME/.kube/config" --kube="tcp://$MINIKUBE_IP:8443" --kube-port=8443 --certs="$HOME/.minikube" --certs-path="$HOME/.minikube" --insecure
