name: Lint
on:
  workflow_dispatch:
  push:
    branches: [ "*" ]
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      SHUTUP: 1
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: lint
      uses: dagger/dagger-for-github@v6
      with:
        version: "0.14.0"
        call: lint
        dagger-flags: "--progress=plain --silent"
